name: Build Android Native APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Change Wrapper Permissions
      # الخطوة دي عشان ندعم ملف الـ gradlew يشتغل من غير مشاكل صلاحيات
      run: chmod +x gradlew

    - name: Build Debug APK
      # الأمر السحري لبناء أي مشروع أندرويد نيتف
      run: ./gradlew assembleDebug

    - name: Upload Finished APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ymusic-native-apk
        path: app/build/outputs/apk/debug/app-debug.apk
